name: Bug report
description: "Found a bug? Report here!"
title: "[BUG] "
labels: ["need testing", "bug"]
assignees:
  - florian-at-v38armageddon
body:
  - type: textarea
    id: describe
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: To Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem.
      placeholder: Add screenshots here
  - type: dropdown
    id: environment
    attributes:
      label: Environment
      description: Please select the environment where you observed the bug.
      multiple: true
      options:
        - "Windows (Microsoft Store)"
        - "Windows (Desktop)"
        - "Vincent OS"
        - "Linux (Flatpak)"
        - "Android"
    validations:
      required: true
  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
      placeholder: Add additional context here
