name: Feature request
description: Do you have a idea? Say here!
title: "[IDEA] "
labels: ["enhancement"]
assignees:
  - florian-at-v38armageddon
body:
  - type: textarea
    id: describe
    attributes:
      label: Describe the feature
      description: A clear and concise description of what the feature is.
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen.
    validations:
      required: true
  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context about the feature request here.
      placeholder: Add additional context here
    validations:
      required: false
